"""Domain model for Detection Alerts."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True)
class MitreAttackMapping:
    """MITRE ATT&CK tactical mapping for detection rules."""

    tactic: str
    technique_id: str
    technique_name: str


@dataclass(frozen=True)
class Alert:
    """Represents a threat detection alert generated by rule evaluation."""

    id: UUID
    rule_id: str
    title: str
    description: str
    severity: float  # 0.0 - 1.0
    confidence: float  # 0.0 - 1.0
    mitre: MitreAttackMapping
    playbook_category: str
    matched_event_ids: list[UUID]
    group_by_key: str
    created_at: datetime
    incident_id: UUID | None = None
    extra_context: dict[str, str | int | float | bool] = field(default_factory=dict)
